version: 2.1
jobs: 
  build: 
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test: 
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run: echo "testing"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - run: echo "hello"
workflows:
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere

