version: 2.1
jobs: 
  hello: 
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run: echo "A first hello"
  second:
    docker:
      -image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run: echo "Double Trouble"
workflows:
  hello_secondary:
    jobs:
      - hello
      - secondary

